import {describe,expect,it} from "vitest";
import {createCityBlockMap,CURRENT_MAP_GENERATION_VERSION} from "../data/map-definitions";
import {CollisionSystem} from "../systems/collision-system";
import {TILE_SIZE} from "../config/game-config";

describe("generated buildings use shared structure segments",()=>{
  it("creates deterministic world-owned walls and doors without legacy building wall obstacles",()=>{const first=createCityBlockMap(0x7812),second=createCityBlockMap(0x7812);expect(CURRENT_MAP_GENERATION_VERSION).toBe(3);expect(first.generatedStructures).toEqual(second.generatedStructures);expect(first.generatedStructures.length).toBeGreaterThan(100);expect(first.generatedStructures.every((structure)=>structure.source==="generated"&&structure.ownership==="world"&&!structure.demolishable&&!structure.refund)).toBe(true);expect(first.obstacles.some((obstacle)=>obstacle.kind==="wall"&&obstacle.id.startsWith("building-"))).toBe(false);expect(new Set(first.generatedStructures.map((structure)=>structure.id)).size).toBe(first.generatedStructures.length);});
  it("supports horizontal, vertical and both diagonal segment directions",()=>{const map=createCityBlockMap(0x1298),directions=new Set(map.generatedStructures.filter((structure)=>structure.buildableId==="wood-wall").map(({placement})=>{const dx=placement.endX-placement.startX,dy=placement.endY-placement.startY;return Math.abs(dx)<.001?"vertical":Math.abs(dy)<.001?"horizontal":dx*dy>0?"diagonal-down":"diagonal-up";}));expect(directions).toEqual(new Set(["horizontal","vertical","diagonal-down","diagonal-up"]));});
  it("replaces each door gap instead of duplicating a wall and uses common collision",()=>{const map=createCityBlockMap(0x4421);for(const door of map.doors){expect(door.source).toBe("generated");expect(door.ownership).toBe("world");expect(map.generatedStructures.some((structure)=>structure.id===door.id&&structure.buildableId==="wood-door")).toBe(true);expect(map.wallSegments.some((wall)=>wall.startX===door.segment!.startX&&wall.startY===door.segment!.startY&&wall.endX===door.segment!.endX&&wall.endY===door.segment!.endY)).toBe(false);}for(const building of map.buildings){const count=map.doors.filter((door)=>door.buildingId===building.id).length;expect(count).toBeGreaterThanOrEqual(1);expect(count).toBeLessThanOrEqual(4);}const wall=map.wallSegments[0]!,collision=new CollisionSystem(map.obstacles,map.doors,map.widthTiles,map.heightTiles,TILE_SIZE,map.wallSegments);expect(collision.blocksVisionWorld((wall.startX+wall.endX)/2,(wall.startY+wall.endY)/2)).toBe(true);});
  it("keeps legacy v2 wall tiles and door ids for old saves",()=>{const legacy=createCityBlockMap(0x4421,2);expect(legacy.generatedStructures).toEqual([]);expect(legacy.obstacles.some((obstacle)=>obstacle.kind==="wall"&&obstacle.id.startsWith("building-"))).toBe(true);expect(legacy.doors.some((door)=>door.id.startsWith("door-building-"))).toBe(true);});
});
