import {describe,expect,it,vi} from "vitest";
import {createOrientedSegmentChain} from "../systems/structure-segment-placement";
import {beginWallDrag,clearWallDrag,createWallDragState,markWallDragCommitted,snapshotWallDrag,updateWallDragPreview} from "../systems/wall-drag-chain-placement";
import {commitStructureSegmentChain} from "../systems/build-transaction";

function chain(count:number){return createOrientedSegmentChain("wood-wall",{x:0,y:0},{x:count*24,y:0},0);}
function transaction(count:number,failAt=-1){const segments=chain(count),created:string[]=[],removed={value:count*4},restore=vi.fn(()=>{removed.value=count*4;});const result=commitStructureSegmentChain({buildableId:"wood-wall",source:{kind:"materials"},segments,dragSequence:7,validateSegment:()=>true,validateSource:(quantity)=>removed.value>=quantity*4,reserveIds:(quantity)=>Array.from({length:quantity},(_,index)=>`wall-${index}`),consumeSource:(quantity)=>{removed.value-=quantity*4;return true;},restoreSource:restore,createAndRegister:(_segment,id,index)=>{if(index===failAt)throw new Error("register");created.push(id);},rollbackCreated:(id)=>{created.splice(created.indexOf(id),1);}});return{result,created,removed,restore};}

describe("wall drag chain snapshot and commit",()=>{
  for(const count of [1,3,5,8])it(`installs all ${count} preview segments`,()=>{const state=createWallDragState();beginWallDrag(state,"wood-wall",{x:0,y:0},0);updateWallDragPreview(state,{x:count*24,y:0},chain(count));const snapshot=snapshotWallDrag(state)!;expect(snapshot.segments).toHaveLength(count);expect(transaction(count).result).toMatchObject({success:true,requestedCount:count,installedCount:count});});
  it("keeps a detached immutable release snapshot until commit completes",()=>{const state=createWallDragState();beginWallDrag(state,"wood-wall",{x:0,y:0},0);updateWallDragPreview(state,{x:72,y:0},chain(3));const snapshot=snapshotWallDrag(state)!;expect(Object.isFrozen(snapshot.segments)).toBe(true);expect(markWallDragCommitted(state,snapshot.dragSequence)).toBe(true);expect(snapshot.segments).toHaveLength(3);expect(clearWallDrag(state,snapshot.dragSequence)).toBe(true);expect(snapshot.segments).toHaveLength(3);});
  it("allows only one finish for a drag sequence",()=>{const state=createWallDragState();beginWallDrag(state,"wood-wall",{x:0,y:0},0);updateWallDragPreview(state,{x:24,y:0},chain(1));expect(markWallDragCommitted(state,state.dragSequence)).toBe(true);expect(markWallDragCommitted(state,state.dragSequence)).toBe(false);});
  it("cancels without a snapshot or install",()=>{const state=createWallDragState();beginWallDrag(state,"wood-wall",{x:0,y:0},0);updateWallDragPreview(state,{x:72,y:0},chain(3));clearWallDrag(state);expect(snapshotWallDrag(state)).toBeNull();});
  it("rejects the whole invalid chain before consuming",()=>{const consume=vi.fn(()=>true),result=commitStructureSegmentChain({buildableId:"wood-wall",source:{kind:"materials"},segments:chain(3),dragSequence:1,validateSegment:(_segment,index)=>index!==1,validateSource:()=>true,reserveIds:()=>[],consumeSource:consume,restoreSource:vi.fn(),createAndRegister:vi.fn(),rollbackCreated:vi.fn()});expect(result).toMatchObject({success:false,installedCount:0,reason:"invalid-chain"});expect(consume).not.toHaveBeenCalled();});
  it("charges the full segment count once",()=>{const {result,removed}=transaction(5);expect(result.installedCount).toBe(5);expect(removed.value).toBe(0);});
  it("rolls every created segment and all material back on registration failure",()=>{const {result,created,removed,restore}=transaction(5,3);expect(result).toMatchObject({success:false,installedCount:0,reason:"creation-failed"});expect(created).toEqual([]);expect(removed.value).toBe(20);expect(restore).toHaveBeenCalledOnce();});
  it("does not replace the preview chain with only its last segment",()=>{const state=createWallDragState();beginWallDrag(state,"wood-wall",{x:0,y:0},0);updateWallDragPreview(state,{x:120,y:0},chain(5));expect(snapshotWallDrag(state)!.segments.map((segment)=>segment.startX)).toEqual([0,24,48,72,96]);});
});
