import { getEquipmentStorageDescription, getItemDefinition, type InventoryRotation, type StorageSlot } from "../data/item-definitions";
import { getInventoryObjectDefinition, isWeaponItemId } from "../data/inventory-object-definitions";
import type { AudioCue } from "../data/audio-definitions";
import { CRAFTING_STATION_LABEL, type CraftingStationKind, type RecipeDefinition } from "../data/recipe-definitions";
import type { CraftAvailability } from "../systems/crafting-system";
import type { InventoryContainerKind, InventoryContainerView, InventoryDropTarget, InventoryItemInstance, InventoryItemLocation, InventoryMoveTarget, InventorySlot, WeaponEquipmentSlot, WeaponEquipmentState } from "../systems/inventory-system";
import { bindItemIconFallbacks, createItemIconMarkup } from "./item-icon";
import { getInventoryItemRenderGeometry, getInventoryRenderStyle, INVENTORY_GRID_METRICS, type InventoryItemRenderGeometry } from "./inventory-item-render-geometry";
import { createInventoryItemView, getInventoryItemViewGeometry } from "./inventory-item-view";
import { createItemGridRowMarkup, packReadonlyGrid } from "./item-grid-row";
import { BUILDABLE_DEFINITIONS, getBuildCostItems, getBuildableCatalogArtPath, type BuildableDefinition, type BuildableKind } from "../data/buildable-definitions";
import type { BuildPlacementSource } from "../systems/build-placement-flow";

export interface BuildTabSelectionIntent { buildableId:BuildableKind; source:BuildPlacementSource; requestedAt:number }

export interface InventoryPanelState {
  containers: ReadonlyArray<InventoryContainerView>; items: ReadonlyArray<InventoryItemInstance>;
  equipment: Readonly<Partial<Record<StorageSlot, string>>>; quickslots: Array<string | null>;
  recipes: readonly RecipeDefinition[]; craftAvailability: Readonly<Record<string, CraftAvailability>>;
  itemCounts: Readonly<Record<string, number>>; weaponEquipment: Readonly<WeaponEquipmentState>;
  developerMode: boolean; inventoryRevision: number;
  craftingStationKind?: CraftingStationKind; craftingStationName?: string;
}

export interface InventoryPanelCallbacks {
  onClose(): void; onCraft(recipeId: string): void; onUseItem(instanceId: string): void;
  onStartBuildPlacement(intent:BuildTabSelectionIntent):boolean;
  onDropItem(instanceId: string): void; onAssignQuickslot(instanceId: string, quickslot: number): void;
  onMoveItem(instanceId: string, target: InventoryMoveTarget): boolean; onRotateItem(instanceId: string): boolean;
  canPlaceItem(instanceId: string, target: InventoryMoveTarget): boolean;
  onEquipItem(instanceId: string): void; onUnequipItem(slot: StorageSlot): void;
  canEquipItemToSlot(instanceId: string, slot: StorageSlot): boolean; onEquipItemToSlot(instanceId: string, slot: StorageSlot): boolean;
  canEquipWeapon(instanceId: string, slot: WeaponEquipmentSlot): boolean; onEquipWeapon(instanceId: string, slot: WeaponEquipmentSlot): boolean;
  onUnequipWeapon(slot: WeaponEquipmentSlot): boolean; onActivateWeapon(slot: WeaponEquipmentSlot): boolean;
  canUnequipItemToGrid(slot: StorageSlot, instanceId: string, target: InventoryMoveTarget): boolean; onUnequipItemToGrid(slot: StorageSlot, instanceId: string, target: InventoryMoveTarget): boolean;
  canUnequipWeaponToGrid(slot: WeaponEquipmentSlot, instanceId: string, target: InventoryMoveTarget): boolean; onUnequipWeaponToGrid(slot: WeaponEquipmentSlot, instanceId: string, target: InventoryMoveTarget): boolean;
  onAudio(cue: AudioCue): void;
}

interface DragState {
  instanceId: string; startX: number; startY: number; dragging: boolean; rotation: InventoryRotation;
  width: number; height: number; grabX: number; grabY: number; source: HTMLElement; cell: number; currentX: number; currentY: number; origin: InventoryItemLocation;
}
export const STORAGE_ROW_ORDER: readonly InventoryContainerKind[] = ["pockets", "shirt", "pants", "belt", "vest", "backpack"];
const CONTAINER_LABELS: Record<InventoryContainerKind, string> = { pockets: "속옷", shirt: "상의", pants: "바지", belt: "벨트", vest: "조끼", backpack: "가방" };

export interface RectLike { left: number; right: number; top: number; width: number; height: number }
export interface DragPlacement { x: number; y: number; cell: number }
export function getItemGridStyle(item: Pick<InventoryItemInstance, "x" | "y" | "width" | "height">): string { return `--item-x:${item.x};--item-y:${item.y};--item-w:${item.width};--item-h:${item.height}`; }
export function getGridCellSize(rect: Pick<RectLike, "width">, columns: number): number { return columns > 0 ? rect.width / columns : 0; }
export function getFootprintPixelSize(width: number, height: number, cellSize: number, cellGap = 0, inset = 4): { width: number; height: number } { return { width: width * cellSize + (width - 1) * cellGap - inset, height: height * cellSize + (height - 1) * cellGap - inset }; }
export function getDragPlacement(clientX: number, clientY: number, rect: Pick<RectLike, "left" | "top" | "width">, columns: number, grabX: number, grabY: number): DragPlacement { const cell = getGridCellSize(rect, columns); return { x: Math.floor((clientX - rect.left) / cell) - grabX, y: Math.floor((clientY - rect.top) / cell) - grabY, cell }; }
export function rotateGrabOffset(grabX: number, grabY: number, width: number, height: number): { grabX: number; grabY: number } { return { grabX: Math.max(0, Math.min(height - 1, height - 1 - grabY)), grabY: Math.max(0, Math.min(width - 1, grabX)) }; }
export function getInventoryContainerDisplayName(kind: InventoryContainerKind): string { return CONTAINER_LABELS[kind]; }
export function getStorageRows(containers: ReadonlyArray<InventoryContainerView>): ReadonlyArray<{ kind: InventoryContainerKind; container?: InventoryContainerView }> { return STORAGE_ROW_ORDER.flatMap((kind) => { const container = containers.find((candidate) => candidate.kind === kind); return kind === "pockets" || container ? [{ kind, container }] : []; }); }
export function getTemporaryEquipmentDropSlot(itemId: string, equipment: Readonly<Partial<Record<StorageSlot, string>>>): StorageSlot | null { const slot = getInventoryObjectDefinition(itemId).storageEquipment?.slot; return slot && !equipment[slot] ? slot : null; }
export function getPopoverPosition(anchor: RectLike, popover: Pick<RectLike, "width" | "height">, viewportWidth: number, viewportHeight: number): { left: number; top: number } { let left = anchor.right + 8; if (left + popover.width > viewportWidth - 8) left = anchor.left - popover.width - 8; return { left: Math.max(8, Math.min(left, viewportWidth - popover.width - 8)), top: Math.max(8, Math.min(anchor.top, viewportHeight - popover.height - 8)) }; }
export type ItemContextAction = "use" | "equip" | "weapon-primary" | "weapon-secondary" | "rotate" | "drop" | "quick";
export function getItemContextActions(itemId: string): ReadonlyArray<ItemContextAction> { const definition = getInventoryObjectDefinition(itemId); const actions: ItemContextAction[] = isWeaponItemId(itemId) ? ["weapon-primary", "weapon-secondary"] : definition.storageEquipment ? ["equip"] : ["use"]; if (definition.inventoryFootprint.width !== definition.inventoryFootprint.height) actions.push("rotate"); actions.push("drop"); if (!definition.storageEquipment && !isWeaponItemId(itemId)) actions.push("quick"); return actions; }
export function createInventorySlotIconMarkup(slot: InventorySlot | null): string { if (!slot) return ""; const item = getInventoryObjectDefinition(slot.itemId); return createItemIconMarkup({ id: item.id, name: item.name, color: item.iconColor, className: "inventory-icon" }); }
export function getEquipmentItemPreviewGeometry(itemId: string, rotation: InventoryRotation = 0): InventoryItemRenderGeometry { return getInventoryItemViewGeometry({ itemId, rotation, metrics: INVENTORY_GRID_METRICS }); }
export function createBuildCatalogRowMarkup(definition:BuildableDefinition,basePath=import.meta.env.BASE_URL):string{const art=definition.catalogArt,view=createInventoryItemView({instanceId:`build:${definition.kind}`,itemId:definition.kind,quantity:1,rotation:0,surface:"build-catalog",catalogArt:{src:getBuildableCatalogArtPath(definition.kind,basePath),name:definition.name,widthCells:art.widthCells,heightCells:art.heightCells},metrics:INVENTORY_GRID_METRICS}),artGrid=`<div class="grid-inventory__surface build-catalog-art" style="--grid-w:${art.widthCells};--grid-h:${art.heightCells}"><div class="grid-inventory__item" style="--item-x:0;--item-y:0;--item-w:${art.widthCells};--item-h:${art.heightCells}">${view}</div></div><small>${definition.name} · 카탈로그 ${art.widthCells}×${art.heightCells}<br>${definition.placementClass}</small>`,header=`<div><b>${definition.name}</b><small>${definition.placementClass==="structure"?"구조물":"가구"} · 체력 ${definition.maximumHealth}</small></div><button data-action="start-build" data-buildable-id="${definition.kind}">배치 시작</button>`;return createItemGridRowMarkup({className:"build-catalog-row",attributes:`data-buildable-id="${definition.kind}"`,header,left:artGrid,right:`<div class="build-catalog-row__costs"></div><p class="build-catalog-row__details"></p><p class="build-catalog-row__source"></p>`});}
export function isBuildIntentExactItemAvailable(intent:BuildTabSelectionIntent|undefined,items:ReadonlyArray<Pick<InventoryItemInstance,"instanceId"|"itemId"|"quantity">>):boolean{if(!intent)return true;const source=intent.source;if(source.kind!=="item")return true;return items.some((item)=>item.instanceId===source.instanceId&&item.itemId===source.itemId&&item.quantity>0);}

export class InventoryPanel {
  readonly root: HTMLDivElement;
  private readonly inventoryView: HTMLDivElement; private readonly craftingView: HTMLDivElement;private readonly buildView:HTMLDivElement;
  private readonly dragGhost: HTMLDivElement; private readonly placementPreview: HTMLDivElement; private readonly popover: HTMLDivElement;
  private state?: InventoryPanelState; private drag?: DragState; private popoverInstanceId?: string;
  private activeTab: "inventory" | "crafting"|"build" = "inventory"; private previewKey = ""; private highlightedDropTarget?: HTMLElement;private buildIntent?:BuildTabSelectionIntent;
  private craftingRenderKey = "";

  constructor(parent: HTMLElement, private readonly callbacks: InventoryPanelCallbacks) {
    this.root = document.createElement("div"); this.root.className = "modal-layer"; this.root.hidden = true;
    this.root.innerHTML = `<section class="inventory-panel pixel-panel"><header><h2>생존 가방</h2><nav class="inventory-tabs"><button data-action="tab" data-tab="inventory">인벤토리</button><button data-action="tab" data-tab="crafting">제작</button><button data-action="tab" data-tab="build">건설</button></nav><button data-action="close">닫기 [Tab]</button></header><div class="inventory-panel__view" data-view="inventory"></div><div class="inventory-panel__view" data-view="crafting" hidden></div><div class="inventory-panel__view build-catalog-view" data-view="build" hidden></div></section>`;
    const inventoryView = this.root.querySelector<HTMLDivElement>('[data-view="inventory"]'),craftingView = this.root.querySelector<HTMLDivElement>('[data-view="crafting"]'),buildView=this.root.querySelector<HTMLDivElement>('[data-view="build"]');
    if (!inventoryView || !craftingView||!buildView) throw new Error("Inventory panel views missing"); this.inventoryView = inventoryView; this.craftingView = craftingView;this.buildView=buildView;this.createBuildRows();
    this.dragGhost = document.createElement("div"); this.dragGhost.className = "inventory-drag-ghost"; this.dragGhost.hidden = true;
    this.placementPreview = document.createElement("div"); this.placementPreview.className = "inventory-placement-preview"; this.placementPreview.hidden = true;
    this.popover = document.createElement("div"); this.popover.className = "item-context-popover pixel-panel"; this.popover.hidden = true;
    this.root.append(this.dragGhost, this.placementPreview, this.popover);
    this.root.addEventListener("click", (event) => this.handleClick(event)); this.root.addEventListener("pointerdown", (event) => this.handlePointerDown(event)); this.root.addEventListener("scroll", () => this.closePopover(), true);
    window.addEventListener("pointermove", this.handlePointerMove); window.addEventListener("pointerup", this.handlePointerUp); document.addEventListener("keydown", this.handleKeyDown); parent.append(this.root);
  }
  show(state: InventoryPanelState): void { this.state = state; this.root.hidden = false; this.render(); this.switchTab(this.activeTab, false); }
  showCrafting(state: InventoryPanelState): void { this.activeTab = "crafting"; this.show(state); }
  showBuild(state:InventoryPanelState):void{this.buildIntent=undefined;this.activeTab="build";this.show(state);}
  openBuildTabForPlacement(intent:BuildTabSelectionIntent,state:InventoryPanelState):void{this.closePopover();this.buildIntent={...intent,source:{...intent.source}};this.activeTab="build";this.show(state);const row=this.buildView.querySelector<HTMLElement>(`[data-buildable-id="${intent.buildableId}"]`);row?.classList.add("is-selected");row?.scrollIntoView({block:"nearest"});}
  hide(): void { this.closePopover(); this.cancelDrag(); this.root.hidden = true; }
  isOpen(): boolean { return !this.root.hidden; }
  update(state: InventoryPanelState): void { this.state = state; if (this.popoverInstanceId && !state.items.some((item) => item.instanceId === this.popoverInstanceId)) this.closePopover(); if (!this.root.hidden) this.render(); }
  destroy(): void { window.removeEventListener("pointermove", this.handlePointerMove); window.removeEventListener("pointerup", this.handlePointerUp); document.removeEventListener("keydown", this.handleKeyDown); this.root.remove(); }

  private render(): void { if (!this.state) return; this.renderInventory(); this.renderCrafting();this.renderBuild(); this.switchTab(this.activeTab, false); if (this.drag?.dragging) this.showTemporaryEquipmentDropTarget(); bindItemIconFallbacks(this.root); }

  private createBuildRows():void{const groups=(["structure","furniture"] as const).map((placementClass)=>`<section class="build-catalog-group"><h3>${placementClass==="structure"?"구조물":"가구·설비"}</h3>${Object.values(BUILDABLE_DEFINITIONS).filter((definition)=>definition.placementClass===placementClass).map((definition)=>createBuildCatalogRowMarkup(definition)).join("")}</section>`).join("");this.buildView.innerHTML=`<p class="build-catalog-summary">재료가 부족해도 모든 항목을 확인할 수 있습니다.</p>${groups}`;}

  private renderBuild():void{if(!this.state)return;for(const definition of Object.values(BUILDABLE_DEFINITIONS)){const row=this.buildView.querySelector<HTMLElement>(`[data-buildable-id="${definition.kind}"]`);if(!row)continue;const costs=getBuildCostItems(definition),exactIntent=this.buildIntent?.buildableId===definition.kind?this.buildIntent:undefined,missingExact=!isBuildIntentExactItemAvailable(exactIntent,this.state.items),affordable=this.state.developerMode||(!missingExact&&costs.every((cost)=> (this.state!.itemCounts[cost.itemId]??0)>=cost.quantity));const button=row.querySelector<HTMLButtonElement>('[data-action="start-build"]'),costsNode=row.querySelector<HTMLElement>(".build-catalog-row__costs"),details=row.querySelector<HTMLElement>(".build-catalog-row__details"),source=row.querySelector<HTMLElement>(".build-catalog-row__source");if(button){button.disabled=!affordable;button.textContent=missingExact?"아이템 없음":affordable?"배치 시작":"비용 부족";}if(costsNode)costsNode.textContent=this.state.developerMode?"비용 ∞ · 개발자 무제한":costs.map((cost)=>`${getItemDefinition(cost.itemId).name} ${this.state!.itemCounts[cost.itemId]??0}/${cost.quantity}`).join(" · ");if(details)details.textContent=`배치: ${definition.placementClass==="structure"?"타일 anchor":"자유 위치·각도"} · 시야 ${definition.blocksVision?"차단":"비차단"}${definition.craftingStationKind?` · ${CRAFTING_STATION_LABEL[definition.craftingStationKind]} 제작대`:definition.category==="power"?" · 전력 설비":""}`;if(source)source.textContent=missingExact?"건축 아이템이 더 이상 존재하지 않습니다.":exactIntent?.source.kind==="item"?`선택한 아이템: ${exactIntent.source.instanceId}`:"";row.classList.toggle("is-selected",this.buildIntent?.buildableId===definition.kind);}}
  private renderInventory(): void {
    if (!this.state) return; const itemsById = new Map(this.state.items.map((item) => [item.instanceId, item]));
    const rows = getStorageRows(this.state.containers).map(({ kind, container }) => {
      const source = container?.sourceItemInstanceId ? itemsById.get(container.sourceItemInstanceId) : undefined;
      const equipment = kind === "pockets" ? `<div class="storage-row__equipment is-built-in"><b>속옷</b><small>항상 사용 가능</small></div>` : source ? `<div class="storage-row__equipment equipment-drop-target" data-equipment-drop-slot="${kind}" data-equipment-equipped-slot="${kind}">${this.itemView(source, "equipment-slot")}<div><b>${getInventoryObjectDefinition(source.itemId).name}</b><button data-action="unequip-item" data-slot="${kind}">해제</button></div></div>` : "";
      if (!container) return "";
      const stored = this.state!.items.filter((item) => item.containerId === container.id).map((item) => {
        const definition = getInventoryObjectDefinition(item.itemId); const quick = this.state!.quickslots.map((id, index) => id === item.itemId ? index + 1 : null).filter(Boolean).join(",");
        const geometry = getInventoryItemViewGeometry({ itemId: item.itemId, rotation: item.rotation, metrics: INVENTORY_GRID_METRICS });
        return `<button class="grid-inventory__item" data-instance-id="${item.instanceId}" style="${getItemGridStyle(item)};${getInventoryRenderStyle(geometry)}" title="${definition.name}">${this.itemView(item, "inventory-grid", quick ? `Q${quick}` : undefined)}</button>`;
      }).join("");
      return createItemGridRowMarkup({ className: "storage-row", attributes: `data-kind="${kind}"`, header: `<h3>${CONTAINER_LABELS[kind]} <small>${container.width}×${container.height}</small></h3>`, left: equipment, right: `<div class="grid-inventory__surface" data-container-id="${container.id}" style="--grid-w:${container.width};--grid-h:${container.height}">${stored}</div>` });
    }).join("");
    const weaponSlots = (["primary", "secondary"] as const).map((slot) => this.renderWeaponSlot(slot, itemsById)).join("");
    this.inventoryView.innerHTML = `<div class="inventory-panel__content"><div class="grid-inventory">${rows}</div><aside><h3>무기 슬롯</h3><div class="weapon-equipment">${weaponSlots}</div><p class="panel-note">인벤토리 무기를 슬롯으로 드래그 · 드래그 중 R: 회전</p></aside></div>`;
  }
  private renderCrafting(): void {
    if (!this.state) return;
    const renderKey = JSON.stringify([this.state.inventoryRevision, this.state.craftingStationKind ?? "hand", this.state.craftingStationName ?? "", this.state.developerMode, this.state.craftAvailability, this.state.itemCounts]);
    if (renderKey === this.craftingRenderKey) return;
    this.craftingRenderKey = renderKey;
    const stationKind = this.state.craftingStationKind ?? "hand";
    const recipes = this.state.recipes.map((recipe) => {
      const availability = this.state!.craftAvailability[recipe.id] ?? "missing-materials";
      const materialItems = Object.entries(recipe.ingredients).map(([itemId, quantity]) => ({ key: itemId, itemId, quantity }));
      const layout = packReadonlyGrid(materialItems, 8);
      const ingredients = layout.placements.map((item) => { const owned = this.state!.itemCounts[item.itemId] ?? 0; const geometry = getInventoryItemViewGeometry({ itemId: item.itemId, rotation: 0, metrics: INVENTORY_GRID_METRICS }); return `<button class="grid-inventory__item recipe-grid__item ${owned < item.quantity ? "is-missing" : ""}" data-readonly-item-id="${item.itemId}" style="${getItemGridStyle(item)};${getInventoryRenderStyle(geometry)}" title="${getItemDefinition(item.itemId).name} ${owned}/${item.quantity}">${this.itemView({ instanceId: `recipe:${recipe.id}:material:${item.itemId}`, itemId: item.itemId, quantity: item.quantity, rotation: 0 }, "readonly-grid")}<span class="recipe-grid__quantity">${owned}/${item.quantity}</span></button>`; }).join("");
      const result = getItemDefinition(recipe.resultItemId); const resultGeometry = getInventoryItemViewGeometry({ itemId: result.id, rotation: 0, metrics: INVENTORY_GRID_METRICS });
      const resultGrid = `<div class="grid-inventory__surface recipe-grid__surface recipe-grid__result" style="--grid-w:${result.inventoryFootprint.width};--grid-h:${result.inventoryFootprint.height}"><button class="grid-inventory__item recipe-grid__item" data-readonly-item-id="${result.id}" style="--item-x:0;--item-y:0;--item-w:${result.inventoryFootprint.width};--item-h:${result.inventoryFootprint.height};${getInventoryRenderStyle(resultGeometry)}">${this.itemView({ instanceId: `recipe:${recipe.id}:result`, itemId: result.id, quantity: recipe.resultQuantity, rotation: 0 }, "readonly-grid")}</button></div>`;
      const materialGrid = `<div class="grid-inventory__surface recipe-grid__surface" style="--grid-w:${layout.columns};--grid-h:${layout.rows}">${ingredients}</div>`;
      const reason = availability === "station-missing" ? "제작대 필요" : availability === "missing-materials" ? "재료 부족" : availability === "inventory-full" ? "수납 공간 부족" : "제작";
      const header = `<div class="craft-recipe__title"><b>${recipe.name} ×${recipe.resultQuantity}</b><small>필요: ${CRAFTING_STATION_LABEL[recipe.requiredStation]}</small><span class="craft-status craft-status--${availability}">${reason}</span></div><button data-action="craft" data-recipe="${recipe.id}" ${availability !== "ready" ? "disabled" : ""}>${reason}</button>`;
      return createItemGridRowMarkup({ className: `craft-recipe ${availability !== "ready" ? "is-disabled" : ""}`, attributes: `data-recipe-id="${recipe.id}" data-availability="${availability}"`, header, left: `<small class="craft-grid-label">제작 결과</small>${resultGrid}`, right: `<small class="craft-grid-label">필요 재료 · 보유/필요</small>${materialGrid}` });
    }).join(""); this.craftingView.innerHTML = `${this.state.developerMode ? '<p class="developer-mode-note">개발자 모드 · 제작 재료 무시</p>' : ""}<p class="crafting-station-context">현재 제작 환경: <b>${this.state.craftingStationName ?? CRAFTING_STATION_LABEL[stationKind]}</b> · 상위 제작대는 하위 조리법을 지원합니다.</p><div class="crafting-list">${recipes}</div>`;
  }
  private itemView(item: Pick<InventoryItemInstance, "instanceId" | "itemId" | "quantity" | "rotation">, surface: "inventory-grid" | "equipment-slot" | "weapon-slot" | "drag-ghost" | "readonly-grid", quickLabel?: string): string { return createInventoryItemView({ ...item, surface, quickLabel, metrics: INVENTORY_GRID_METRICS }); }
  private renderWeaponSlot(slot: WeaponEquipmentSlot, itemsById: ReadonlyMap<string, InventoryItemInstance>): string { if (!this.state) return ""; const instanceId = slot === "primary" ? this.state.weaponEquipment.primaryInstanceId : this.state.weaponEquipment.secondaryInstanceId; const item = instanceId ? itemsById.get(instanceId) : undefined; const active = this.state.weaponEquipment.activeSlot === slot && !!item; const label = slot === "primary" ? "주무기" : "보조무기"; if (!item) return `<div class="weapon-equipment__slot equipment-drop-target is-empty" data-weapon-drop-slot="${slot}"><b>${label}</b><small>무기를 여기에 드래그</small></div>`; const definition = getInventoryObjectDefinition(item.itemId); return `<div class="weapon-equipment__slot equipment-drop-target ${active ? "is-active" : ""}" data-weapon-drop-slot="${slot}" data-weapon-equipped-slot="${slot}">${this.itemView(item, "weapon-slot")}<div><b>${label} · ${definition.name}</b><small>${item.width}×${item.height}</small><button data-action="activate-weapon" data-slot="${slot}" ${active ? "disabled" : ""}>${active ? "사용 중" : "사용"}</button><button data-action="unequip-weapon" data-slot="${slot}">해제</button></div></div>`; }

  private handleClick(event: Event): void {
    const readonlyItem = (event.target as HTMLElement).closest<HTMLElement>("[data-readonly-item-id]");
    if (readonlyItem?.dataset.readonlyItemId) { this.openReadonlyPopover(readonlyItem, readonlyItem.dataset.readonlyItemId); return; }
    const target = (event.target as HTMLElement).closest<HTMLButtonElement>("button[data-action]"); if (!target) { if (!(event.target as HTMLElement).closest(".item-context-popover,.grid-inventory__item")) this.closePopover(); return; }
    const action = target.dataset.action; if (action === "tab" && target.dataset.tab) { this.switchTab(target.dataset.tab as "inventory" | "crafting"|"build", true); return; }
    if (action === "close") { this.callbacks.onAudio("ui-click"); this.callbacks.onClose(); return; }
    if (action === "craft" && target.dataset.recipe) this.callbacks.onCraft(target.dataset.recipe);
    if(action==="start-build"&&target.dataset.buildableId&&this.state){const buildableId=target.dataset.buildableId as BuildableKind,source=this.buildIntent?.buildableId===buildableId?this.buildIntent.source:this.state.developerMode?{kind:"developer" as const}:{kind:"materials" as const},intent:BuildTabSelectionIntent={buildableId,source,requestedAt:Date.now()};if(this.callbacks.onStartBuildPlacement(intent)){this.buildIntent=undefined;this.hide();}return;}
    if (action === "unequip-item" && target.dataset.slot) this.callbacks.onUnequipItem(target.dataset.slot as StorageSlot);
    if (action === "activate-weapon" && target.dataset.slot) this.callbacks.onActivateWeapon(target.dataset.slot as WeaponEquipmentSlot);
    if (action === "unequip-weapon" && target.dataset.slot) this.callbacks.onUnequipWeapon(target.dataset.slot as WeaponEquipmentSlot);
    const instanceId = target.dataset.instanceId; if (!instanceId) return;
    if (action === "use-item") this.callbacks.onUseItem(instanceId); if (action === "drop-item") this.callbacks.onDropItem(instanceId); if (action === "equip-item") this.callbacks.onEquipItem(instanceId);
    if (action === "equip-primary") this.callbacks.onEquipWeapon(instanceId, "primary"); if (action === "equip-secondary") this.callbacks.onEquipWeapon(instanceId, "secondary");
    if (action === "rotate-item") { const success = this.callbacks.onRotateItem(instanceId); this.callbacks.onAudio(success ? "item-rotate" : "inventory-invalid"); }
    if (action === "assign-item") { this.callbacks.onAudio("ui-click"); this.callbacks.onAssignQuickslot(instanceId, Number(target.dataset.quickslot)); } this.closePopover();
  }
  private switchTab(tab: "inventory" | "crafting"|"build", playSound: boolean): void { const changed = this.activeTab !== tab; this.activeTab = tab; this.inventoryView.hidden = tab !== "inventory"; this.craftingView.hidden = tab !== "crafting";this.buildView.hidden=tab!=="build"; for (const button of this.root.querySelectorAll<HTMLButtonElement>('[data-action="tab"]')) button.classList.toggle("is-active", button.dataset.tab === tab); if (playSound && changed) this.callbacks.onAudio("ui-tab"); if (changed) { this.closePopover(); this.cancelDrag(); } }
  private handlePointerDown(event: PointerEvent): void {
    if (event.button !== 0 || (event.target as HTMLElement).closest("button[data-action]")) return; const source = (event.target as HTMLElement).closest<HTMLElement>(".inventory-item-frame"); const instanceId = source?.dataset.instanceId; const item = this.state?.items.find((candidate) => candidate.instanceId === instanceId); if (!source || !item) return;
    const surface = source.closest<HTMLElement>(".grid-inventory__surface"); const equipmentSlot = source.closest<HTMLElement>("[data-equipment-equipped-slot]")?.dataset.equipmentEquippedSlot as StorageSlot | undefined; const weaponSlot = source.closest<HTMLElement>("[data-weapon-equipped-slot]")?.dataset.weaponEquippedSlot as WeaponEquipmentSlot | undefined;
    const origin: InventoryItemLocation | null = surface?.dataset.containerId ? { kind: "container", containerId: surface.dataset.containerId, x: item.x, y: item.y } : equipmentSlot ? { kind: "equipment", slot: equipmentSlot } : weaponSlot ? { kind: "weapon", slot: weaponSlot } : null; if (!origin) return;
    this.closePopover(); const cell = INVENTORY_GRID_METRICS.cellSize; const sourceRect = source.getBoundingClientRect();
    const grabX = Math.max(0, Math.min(item.width - 1, Math.floor((event.clientX - sourceRect.left) / cell))); const grabY = Math.max(0, Math.min(item.height - 1, Math.floor((event.clientY - sourceRect.top) / cell)));
    this.drag = { instanceId: item.instanceId, startX: event.clientX, startY: event.clientY, dragging: false, rotation: item.rotation, width: item.width, height: item.height, grabX, grabY, source, cell, currentX: event.clientX, currentY: event.clientY, origin }; this.renderGhost(item);
  }
  private readonly handlePointerMove = (event: PointerEvent): void => { if (!this.drag) return; this.drag.currentX = event.clientX; this.drag.currentY = event.clientY; if (!this.drag.dragging && Math.hypot(event.clientX - this.drag.startX, event.clientY - this.drag.startY) >= 5) { this.drag.dragging = true; this.drag.source.classList.add("is-dragging"); this.showTemporaryEquipmentDropTarget(); this.callbacks.onAudio("inventory-pickup"); } if (!this.drag.dragging) return; this.positionGhost(event.clientX, event.clientY); this.updatePlacementPreview(event.clientX, event.clientY); };
  private readonly handlePointerUp = (event: PointerEvent): void => { const drag = this.drag; if (!drag) return; if (!drag.dragging) { this.drag = undefined; this.dragGhost.hidden = true; if (drag.origin.kind === "container") this.openPopover(drag.source, drag.instanceId); return; } const target = this.getDropTarget(event.clientX, event.clientY); let success = false; let noOp = false; let equipmentAudioHandled = false;
    if (target?.kind === "weapon") { if (drag.origin.kind === "weapon" && drag.origin.slot === target.slot) { success = true; noOp = true; } else if (drag.origin.kind !== "equipment") success = this.callbacks.onEquipWeapon(drag.instanceId, target.slot); }
    else if (target?.kind === "equipment") { if (drag.origin.kind === "equipment" && drag.origin.slot === target.slot) { success = true; noOp = true; } else if (drag.origin.kind === "container") { success = this.callbacks.onEquipItemToSlot(drag.instanceId, target.slot); equipmentAudioHandled = success; } }
    else if (target?.kind === "container") { if (drag.origin.kind === "container") success = this.callbacks.onMoveItem(drag.instanceId, target); else if (drag.origin.kind === "equipment") { success = this.callbacks.onUnequipItemToGrid(drag.origin.slot, drag.instanceId, target); equipmentAudioHandled = success; } else success = this.callbacks.onUnequipWeaponToGrid(drag.origin.slot, drag.instanceId, target); }
    if (!success) this.callbacks.onAudio("inventory-invalid"); else if (!noOp && !equipmentAudioHandled) this.callbacks.onAudio("inventory-drop"); this.cancelDrag(); };
  private getDropTarget(clientX: number, clientY: number): InventoryDropTarget | null { if (!this.drag) return null; const hovered = document.elementFromPoint(clientX, clientY); const weaponSlot = hovered?.closest<HTMLElement>("[data-weapon-drop-slot]")?.dataset.weaponDropSlot as WeaponEquipmentSlot | undefined; if (weaponSlot) return { kind: "weapon", slot: weaponSlot }; const equipmentSlot = hovered?.closest<HTMLElement>("[data-equipment-drop-slot]")?.dataset.equipmentDropSlot as StorageSlot | undefined; if (equipmentSlot) return { kind: "equipment", slot: equipmentSlot }; const surface = hovered?.closest<HTMLElement>(".grid-inventory__surface"); if (!surface?.dataset.containerId) return null; const columns = Number(surface.style.getPropertyValue("--grid-w")); const placement = getDragPlacement(clientX, clientY, surface.getBoundingClientRect(), columns, this.drag.grabX, this.drag.grabY); return { kind: "container", containerId: surface.dataset.containerId, x: placement.x, y: placement.y, rotation: this.drag.rotation }; }
  private updatePlacementPreview(clientX: number, clientY: number): void { if (!this.drag || !this.state) return; const hovered = document.elementFromPoint(clientX, clientY); const target = this.getDropTarget(clientX, clientY); if (target?.kind === "weapon") { const element = hovered?.closest<HTMLElement>("[data-weapon-drop-slot]") ?? undefined; const valid = this.drag.origin.kind === "weapon" && this.drag.origin.slot === target.slot ? true : this.drag.origin.kind !== "equipment" && this.callbacks.canEquipWeapon(this.drag.instanceId, target.slot); this.highlightDropTarget(element, valid); this.placementPreview.hidden = true; return; } if (target?.kind === "equipment") { const element = hovered?.closest<HTMLElement>("[data-equipment-drop-slot]") ?? undefined; const valid = this.drag.origin.kind === "equipment" ? this.drag.origin.slot === target.slot : this.drag.origin.kind === "container" && this.callbacks.canEquipItemToSlot(this.drag.instanceId, target.slot); this.highlightDropTarget(element, valid); this.placementPreview.hidden = true; return; } this.highlightDropTarget(); const surface = hovered?.closest<HTMLElement>(".grid-inventory__surface"); if (!surface || !target || target.kind !== "container") { this.placementPreview.hidden = true; this.previewKey = ""; return; } const valid = this.drag.origin.kind === "container" ? this.callbacks.canPlaceItem(this.drag.instanceId, target) : this.drag.origin.kind === "equipment" ? this.callbacks.canUnequipItemToGrid(this.drag.origin.slot, this.drag.instanceId, target) : this.callbacks.canUnequipWeaponToGrid(this.drag.origin.slot, this.drag.instanceId, target); const key = `${target.containerId}:${target.x}:${target.y}:${target.rotation}:${this.state.inventoryRevision}:${valid}`; if (key === this.previewKey) return; this.previewKey = key; surface.append(this.placementPreview); this.placementPreview.hidden = false; this.placementPreview.classList.toggle("is-valid", valid); this.placementPreview.classList.toggle("is-invalid", !valid); const item = this.state.items.find((candidate) => candidate.instanceId === this.drag!.instanceId); const geometry = item ? getInventoryItemRenderGeometry(getInventoryObjectDefinition(item.itemId).inventoryFootprint, target.rotation ?? item.rotation, INVENTORY_GRID_METRICS.cellSize, INVENTORY_GRID_METRICS.cellGap, 1) : null; this.placementPreview.style.cssText = `--item-x:${target.x};--item-y:${target.y};--item-w:${this.drag.width};--item-h:${this.drag.height}${geometry ? `;${getInventoryRenderStyle(geometry)}` : ""}`; }
  private highlightDropTarget(element?: HTMLElement, valid = false): void { if (this.highlightedDropTarget !== element) this.highlightedDropTarget?.classList.remove("is-drop-valid", "is-drop-invalid"); this.highlightedDropTarget = element; if (element) { element.classList.toggle("is-drop-valid", valid); element.classList.toggle("is-drop-invalid", !valid); } }
  private renderGhost(item: InventoryItemInstance): void { if (!this.drag) return; const preview = { ...item, rotation: this.drag.rotation, width: this.drag.width, height: this.drag.height }; const geometry = getInventoryItemViewGeometry({ itemId: item.itemId, rotation: this.drag.rotation, metrics: INVENTORY_GRID_METRICS }); this.dragGhost.innerHTML = this.itemView(preview, "drag-ghost"); this.dragGhost.style.width = `${geometry.frameWidthPx}px`; this.dragGhost.style.height = `${geometry.frameHeightPx}px`; bindItemIconFallbacks(this.dragGhost); }
  private positionGhost(clientX: number, clientY: number): void { if (!this.drag) return; this.dragGhost.hidden = false; this.dragGhost.style.left = `${clientX - this.drag.grabX * this.drag.cell - this.drag.cell / 2}px`; this.dragGhost.style.top = `${clientY - this.drag.grabY * this.drag.cell - this.drag.cell / 2}px`; }
  private rotateDrag(): void { if (!this.drag || !this.drag.dragging) return; const item = this.state?.items.find((candidate) => candidate.instanceId === this.drag!.instanceId); if (!item || item.width === item.height) return; const grab = rotateGrabOffset(this.drag.grabX, this.drag.grabY, this.drag.width, this.drag.height); [this.drag.width, this.drag.height] = [this.drag.height, this.drag.width]; this.drag.rotation = this.drag.rotation === 0 ? 1 : 0; this.drag.grabX = grab.grabX; this.drag.grabY = grab.grabY; this.previewKey = ""; this.renderGhost(item); this.positionGhost(this.drag.currentX, this.drag.currentY); this.updatePlacementPreview(this.drag.currentX, this.drag.currentY); this.callbacks.onAudio("item-rotate"); }
  private openPopover(anchor: HTMLElement, instanceId: string): void { const item = this.state?.items.find((candidate) => candidate.instanceId === instanceId); if (!item) return; const definition = getInventoryObjectDefinition(item.itemId); const storage = !isWeaponItemId(item.itemId) ? getEquipmentStorageDescription(getItemDefinition(item.itemId)) : null; const actions = getItemContextActions(item.itemId); this.popoverInstanceId = instanceId; this.popover.innerHTML = `<b>${definition.name}</b><small>${definition.description}${storage ? `<br>${storage}` : ""}</small><div>${actions.includes("use") ? `<button data-action="use-item" data-instance-id="${instanceId}">사용</button>` : ""}${actions.includes("equip") ? `<button data-action="equip-item" data-instance-id="${instanceId}">장착</button>` : ""}${actions.includes("weapon-primary") ? `<button data-action="equip-primary" data-instance-id="${instanceId}">주무기에 장착</button>` : ""}${actions.includes("weapon-secondary") ? `<button data-action="equip-secondary" data-instance-id="${instanceId}">보조무기에 장착</button>` : ""}${actions.includes("rotate") ? `<button data-action="rotate-item" data-instance-id="${instanceId}">회전 [R]</button>` : ""}<button data-action="drop-item" data-instance-id="${instanceId}">버리기</button>${actions.includes("quick") ? [0, 1, 2, 3, 4].map((quickslot) => `<button data-action="assign-item" data-instance-id="${instanceId}" data-quickslot="${quickslot}">${quickslot + 1}</button>`).join("") : ""}</div>`; this.popover.hidden = false; const position = getPopoverPosition(anchor.getBoundingClientRect(), this.popover.getBoundingClientRect(), window.innerWidth, window.innerHeight); this.popover.style.left = `${position.left}px`; this.popover.style.top = `${position.top}px`; }
  private openReadonlyPopover(anchor: HTMLElement, itemId: string): void { const definition = getInventoryObjectDefinition(itemId); this.popoverInstanceId = undefined; this.popover.innerHTML = `<b>${definition.name}</b><small>${definition.description}</small>`; this.popover.hidden = false; const position = getPopoverPosition(anchor.getBoundingClientRect(), this.popover.getBoundingClientRect(), window.innerWidth, window.innerHeight); this.popover.style.left = `${position.left}px`; this.popover.style.top = `${position.top}px`; }
  private closePopover(): void { this.popover.hidden = true; this.popoverInstanceId = undefined; }
  private showTemporaryEquipmentDropTarget(): void { this.removeTemporaryEquipmentDropTarget(); if (!this.drag || !this.state || this.drag.origin.kind !== "container") return; const item = this.state.items.find((candidate) => candidate.instanceId === this.drag!.instanceId); if (!item) return; const slot = getTemporaryEquipmentDropSlot(item.itemId, this.state.equipment); if (!slot) return; const aside = this.inventoryView.querySelector("aside"); if (!aside) return; const target = document.createElement("div"); target.className = "temporary-equipment-drop-target equipment-drop-target is-empty"; target.dataset.equipmentDropSlot = slot; target.innerHTML = `<b>${CONTAINER_LABELS[slot]}에 장착</b><small>드래그하는 동안만 표시</small>`; aside.append(target); }
  private removeTemporaryEquipmentDropTarget(): void { this.inventoryView.querySelector(".temporary-equipment-drop-target")?.remove(); }
  private cancelDrag(): void { this.drag?.source.classList.remove("is-dragging"); this.highlightDropTarget(); this.removeTemporaryEquipmentDropTarget(); this.drag = undefined; this.dragGhost.hidden = true; this.placementPreview.hidden = true; this.previewKey = ""; }
  private readonly handleKeyDown = (event: KeyboardEvent): void => { if (this.root.hidden) return; if (event.key.toLowerCase() === "r" && this.drag?.dragging) { event.preventDefault(); this.rotateDrag(); return; } if (event.key === "Escape") { event.preventDefault(); this.callbacks.onClose(); } };
}
